import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className='bg-gradient-to-b from-gray-600 to-gray-200'>
        {children}
      </body>
    </html>
  );
}
